#!/usr/bin/env python3
"""Compile the knowledge base.

Reads every file in content/ (.md and .yaml), concatenates them into a single
knowledge-base string with section headers, and writes the result to
netlify/functions/lib/knowledge.mjs as:

    export const KB = <json-encoded string>;

The KB is generated at build time and is gitignored. Stdlib + pyyaml only.
"""
import json
import os
import sys

try:
    import yaml
except ImportError:
    yaml = None

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTENT_DIR = os.path.join(ROOT, "content")
OUT_PATH = os.path.join(ROOT, "netlify", "functions", "lib", "knowledge.mjs")


def yaml_to_text(raw):
    """Render a YAML document to readable indented text. Falls back to raw."""
    if yaml is None:
        return raw
    try:
        data = yaml.safe_load(raw)
    except Exception:
        return raw
    lines = []

    def walk(node, indent=0):
        pad = "  " * indent
        if isinstance(node, dict):
            for k, v in node.items():
                if isinstance(v, (dict, list)):
                    lines.append(f"{pad}{k}:")
                    walk(v, indent + 1)
                else:
                    lines.append(f"{pad}{k}: {v}")
        elif isinstance(node, list):
            for item in node:
                if isinstance(item, (dict, list)):
                    # Mark the start of each complex item with a bullet so its
                    # fields stay associated (e.g. each link's label + url),
                    # then indent the item's contents one level deeper.
                    lines.append(f"{pad}-")
                    walk(item, indent + 1)
                else:
                    lines.append(f"{pad}- {item}")
        else:
            lines.append(f"{pad}{node}")

    walk(data)
    return "\n".join(lines)


def build():
    if not os.path.isdir(CONTENT_DIR):
        print(f"content directory not found: {CONTENT_DIR}", file=sys.stderr)
        sys.exit(1)

    sections = []
    files = sorted(
        f for f in os.listdir(CONTENT_DIR)
        if f.endswith((".md", ".yaml", ".yml"))
    )
    if not files:
        print(f"no .md or .yaml files found in {CONTENT_DIR}", file=sys.stderr)
        sys.exit(1)

    for name in files:
        path = os.path.join(CONTENT_DIR, name)
        with open(path, "r", encoding="utf-8") as fh:
            raw = fh.read().strip()
        if name.endswith((".yaml", ".yml")):
            body = yaml_to_text(raw)
        else:
            body = raw
        header = f"===== SOURCE: {name} ====="
        sections.append(f"{header}\n{body}")

    kb = "\n\n".join(sections).strip() + "\n"

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    mjs = (
        "// AUTO-GENERATED by scripts/build_kb.py. Do not edit by hand.\n"
        "// Regenerate with: python3 scripts/build_kb.py\n"
        f"export const KB = {json.dumps(kb)};\n"
    )
    with open(OUT_PATH, "w", encoding="utf-8") as fh:
        fh.write(mjs)

    print(f"Wrote {OUT_PATH} ({len(kb)} chars from {len(files)} file(s))")
    return OUT_PATH


if __name__ == "__main__":
    build()
